# Generated by Django 4.0.2 on 2022-02-14 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UWFX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='logger',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
