# Generated by Django 4.0.2 on 2022-03-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWFX', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen',
            old_name='cinema_fk',
            new_name='cinema',
        ),
    ]
