# Generated by Django 4.0.2 on 2022-03-09 18:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UWFX', '0002_logmessage_logger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('cardNumber', models.CharField(max_length=17)),
                ('expiryDate', models.CharField(max_length=7)),
                ('discountRate', models.IntegerField(verbose_name=11)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetNumber', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentQuantity', models.IntegerField(verbose_name=11)),
                ('childQuantity', models.IntegerField(verbose_name=11)),
                ('adultQuantity', models.IntegerField(verbose_name=11)),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialDist', models.BooleanField(verbose_name=False)),
            ],
            options={
                'db_table': 'Cinema',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.address')),
            ],
            options={
                'db_table': 'Club',
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landline', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')])),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')])),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'ContactDetails',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('age', models.IntegerField(verbose_name=11)),
                ('duration', models.FloatField(verbose_name=11)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Film',
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('dob', models.DateField(null=True)),
                ('number', models.IntegerField(unique=True, verbose_name=11)),
                ('password', models.CharField(blank=True, default=uuid.uuid4, max_length=20, unique=True)),
                ('club_fk', models.ForeignKey(null='None', on_delete=django.db.models.deletion.CASCADE, to='UWFX.club')),
            ],
            options={
                'db_table': 'Representative',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name=11)),
                ('screenNumber', models.IntegerField(verbose_name=11)),
                ('cinema_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.cinema')),
            ],
            options={
                'db_table': 'Screen',
            },
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('ticketsSold', models.IntegerField(verbose_name=11)),
                ('film_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.film')),
                ('screen_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.screen')),
            ],
            options={
                'db_table': 'Showing',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentPrice', models.FloatField(verbose_name=11)),
                ('childPrice', models.FloatField(verbose_name=11)),
                ('adultPrice', models.FloatField(verbose_name=11)),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name=11)),
                ('data', models.DateField(null=True)),
                ('account_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.account')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.representative')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.AddField(
            model_name='club',
            name='contactDetails_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.contactdetails'),
        ),
        migrations.AddField(
            model_name='account',
            name='club_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.club'),
        ),
    ]
