# Generated by Django 4.0.2 on 2022-03-10 16:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UWFX', '0003_alter_showing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showing',
            old_name='film_fk',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='showing',
            old_name='screen_fk',
            new_name='screen',
        ),
        migrations.RemoveField(
            model_name='showing',
            name='ticketsSold',
        ),
        migrations.AlterField(
            model_name='showing',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
