# Generated by Django 4.0.3 on 2022-03-13 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UWFX', '0004_rename_film_fk_showing_film_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='address_fk',
        ),
        migrations.RemoveField(
            model_name='club',
            name='contactDetails_fk',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_fk',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='club_fk',
        ),
        migrations.AlterField(
            model_name='representative',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='password',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='ContactDetails',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
