# Generated by Django 4.0.3 on 2022-03-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWFX', '0005_remove_club_address_fk_remove_club_contactdetails_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('cardNumber', models.CharField(max_length=17)),
                ('expiryDate', models.CharField(max_length=7)),
                ('discountRate', models.IntegerField(verbose_name=11)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name=11)),
                ('data', models.DateField(null=True)),
                ('account_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.account')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.representative')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('streetNumber', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=7)),
                ('landline', models.IntegerField(verbose_name='landline')),
                ('mobile', models.IntegerField(verbose_name='Mobile')),
                ('email', models.EmailField(max_length=50)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.representative')),
            ],
            options={
                'db_table': 'Club',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.club'),
        ),
    ]
