# Generated by Django 4.0.3 on 2022-03-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWFX', '0006_account_transaction_club_account_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='representative',
        ),
    ]
