# Generated by Django 4.0.3 on 2022-03-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWFX', '0007_remove_transaction_representative'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
