# Generated by Django 4.0.3 on 2022-03-13 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWFX', '0008_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name=11)),
                ('data', models.DateField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.account')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWFX.representative')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
    ]
